///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ServicesModelServices {
/*
{
  "id": 1,
  "name": "Web Development",
  "description": "At BINGO Agency, we excel in web development, harnessing cutting-edge technologies to craft dynamic, responsive, and user-friendly websites. Our team of skilled developers is proficient in creating custom web solutions that not only meet your business needs but also enhance your online presence. Whether you require a simple informational website or a complex e-commerce platform, our web development services ensure top-notch performance, security, and scalability, keeping you ahead in the digital realm.",
  "image": "img/services/web_development.jpg",
  "slug": "web_development",
  "tags": [
    "web"
  ]
}
*/

  int? id;
  String? name;
  String? description;
  String? image;
  String? slug;
  List<String?>? tags;

  ServicesModelServices({
    this.id,
    this.name,
    this.description,
    this.image,
    this.slug,
    this.tags,
  });
  ServicesModelServices.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    description = json['description']?.toString();
    image = json['image']?.toString();
    slug = json['slug']?.toString();
    if (json['tags'] != null) {
      final v = json['tags'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      tags = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['description'] = description;
    data['image'] = image;
    data['slug'] = slug;
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['tags'] = arr0;
    }
    return data;
  }
}

class ServicesModel {
/*
{
  "services": [
    {
      "id": 1,
      "name": "Web Development",
      "description": "At BINGO Agency, we excel in web development, harnessing cutting-edge technologies to craft dynamic, responsive, and user-friendly websites. Our team of skilled developers is proficient in creating custom web solutions that not only meet your business needs but also enhance your online presence. Whether you require a simple informational website or a complex e-commerce platform, our web development services ensure top-notch performance, security, and scalability, keeping you ahead in the digital realm.",
      "image": "img/services/web_development.jpg",
      "slug": "web_development",
      "tags": [
        "web"
      ]
    }
  ]
}
*/

  List<ServicesModelServices?>? services;

  ServicesModel({
    this.services,
  });
  ServicesModel.fromJson(Map<String, dynamic> json) {
    if (json['services'] != null) {
      final v = json['services'];
      final arr0 = <ServicesModelServices>[];
      v.forEach((v) {
        arr0.add(ServicesModelServices.fromJson(v));
      });
      services = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (services != null) {
      final v = services;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['services'] = arr0;
    }
    return data;
  }
}
